spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/app
    username: app
    password: app
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: TRUE
      hibernate.jdbc.time_zone: UTC
  h2:
    console.enabled: true

server:
  port: 8080
